# Generated by Django 4.2.17 on 2026-04-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_opening_balance_payment_mobile_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mobile_network',
            field=models.CharField(blank=True, choices=[('MTN_MOMO', 'MTN MoMo'), ('AIRTEL_MONEY', 'Airtel Money'), ('OTHER', 'Other mobile wallet')], help_text='When paying by mobile money, which network was used (for reconciliation).', max_length=16),
        ),
    ]
