# Generated by Django 4.2.17 on 2026-05-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_payment_mobile_network"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundMessageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message_type",
                    models.CharField(
                        choices=[("FEE_REMINDER", "Fee reminder"), ("PAYMENT_RECEIPT", "Payment receipt")],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("WHATSAPP", "WhatsApp")],
                        default="SMS",
                        max_length=16,
                    ),
                ),
                ("phone_raw", models.CharField(blank=True, max_length=64)),
                ("phone_normalized", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("DRY_RUN", "Dry run"),
                            ("NO_PHONE", "No phone"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=128)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_logs",
                        to="finance.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_logs",
                        to="finance.payment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["message_type", "channel", "status"], name="finance_outb_message_868d02_idx"),
                    models.Index(fields=["created_at"], name="finance_outb_created_0cff12_idx"),
                ],
            },
        ),
    ]
