# Generated by Django 4.2.17 on 2026-05-04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_integrations_webhooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessagelog",
            name="provider_delivery_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="outboundmessagelog",
            name="provider_delivery_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InboundWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="WHATSAPP", max_length=64)),
                ("event_type", models.CharField(blank=True, max_length=64)),
                ("signature_valid", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("matched_message_logs", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["provider", "signature_valid", "created_at"], name="finance_inb_provide_4c5fc4_idx")],
            },
        ),
        migrations.CreateModel(
            name="WebhookRetryQueueItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("next_attempt_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("last_error_message", models.TextField(blank=True)),
                ("last_status_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retry_items",
                        to="finance.webhookendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ("next_attempt_at", "id"),
                "indexes": [
                    models.Index(fields=["is_active", "next_attempt_at"], name="finance_web_is_acti_048b64_idx"),
                    models.Index(fields=["event_type", "is_active"], name="finance_web_event_t_5154d9_idx"),
                ],
            },
        ),
    ]
