# Generated by Django 5.2.13 on 2026-05-12 17:04

from django.db import migrations, models


def seed_communication_templates(apps, schema_editor):
    CommunicationTemplate = apps.get_model("finance", "CommunicationTemplate")
    if CommunicationTemplate.objects.exists():
        return
    CommunicationTemplate.objects.bulk_create(
        [
            CommunicationTemplate(
                code="fee_reminder_default",
                name="Default fee reminder",
                message_type="FEE_REMINDER",
                channel_hint="ANY",
                body=(
                    "Hello {{parent_name}}, this is {{school_name}}. "
                    "Fee reminder for {{student_name}}: {{amount}} {{currency}} "
                    "(invoice {{invoice_ref}}, due {{due_date}}). Thank you."
                ),
                sort_order=10,
            ),
            CommunicationTemplate(
                code="payment_receipt_default",
                name="Default payment receipt",
                message_type="PAYMENT_RECEIPT",
                channel_hint="ANY",
                body=(
                    "Hello {{parent_name}}, {{school_name}} confirms payment of "
                    "{{amount}} {{currency}} for {{student_name}}. Reference: {{invoice_ref}}."
                ),
                sort_order=20,
            ),
            CommunicationTemplate(
                code="absence_alert_default",
                name="Default absence alert",
                message_type="ABSENCE_ALERT",
                channel_hint="ANY",
                body=(
                    "{{school_name}}: {{student_name}} was marked absent on {{date}}. "
                    "Please contact the school if this is unexpected."
                ),
                sort_order=30,
            ),
            CommunicationTemplate(
                code="urgent_announcement_default",
                name="Default urgent announcement",
                message_type="URGENT_ANNOUNCEMENT",
                channel_hint="ANY",
                body="{{school_name}} — URGENT: {{announcement_title}}\n\n{{announcement_body}}",
                sort_order=40,
            ),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_webhook_retry_and_inbound"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("FEE_REMINDER", "Fee reminder"),
                            ("PAYMENT_RECEIPT", "Payment receipt"),
                            ("ABSENCE_ALERT", "Absence alert"),
                            ("URGENT_ANNOUNCEMENT", "Urgent announcement"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel_hint",
                    models.CharField(
                        choices=[("ANY", "Any channel"), ("SMS", "SMS"), ("WHATSAPP", "WhatsApp")],
                        default="ANY",
                        help_text="Hint for staff; sending code may still use another channel based on settings.",
                        max_length=16,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text. Use placeholders like {{student_name}} — see product docs for the full list.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.RunPython(seed_communication_templates, migrations.RunPython.noop),
    ]
