# Generated by Django 4.2.17 on 2026-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_update_default_template_links'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inboundwebhookevent',
            new_name='finance_inb_provide_dc2336_idx',
            old_name='finance_inb_provide_4c5fc4_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundmessagelog',
            new_name='finance_out_message_b96b9b_idx',
            old_name='finance_outb_message_868d02_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundmessagelog',
            new_name='finance_out_created_e4e2c7_idx',
            old_name='finance_outb_created_0cff12_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='finance_web_event_t_0adddb_idx',
            old_name='finance_web_event_t_630530_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookretryqueueitem',
            new_name='finance_web_is_acti_dd0b84_idx',
            old_name='finance_web_is_acti_048b64_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookretryqueueitem',
            new_name='finance_web_event_t_0bad61_idx',
            old_name='finance_web_event_t_5154d9_idx',
        ),
        migrations.AlterField(
            model_name='outboundmessagelog',
            name='message_type',
            field=models.CharField(choices=[('FEE_REMINDER', 'Fee reminder'), ('PAYMENT_RECEIPT', 'Payment receipt'), ('ABSENCE_ALERT', 'Absence alert'), ('URGENT_ANNOUNCEMENT', 'Urgent announcement')], max_length=32),
        ),
    ]
