# Generated by Django 4.2.17 on 2026-06-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_biometric_meeting_sso_models'),
        ('finance', '0009_rename_finance_inb_provide_4c5fc4_idx_finance_inb_provide_dc2336_idx_and_more'),
    ]

    operations = [
    ]
