# Generated by Django 4.2.17 on 2026-06-18 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_merge_20260618_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationtemplate',
            options={'ordering': ('sort_order', 'code')},
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='finance_jou_source_345703_idx',
            old_name='finance_journal_source_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='finance_jou_account_85c4ce_idx',
            old_name='finance_journalline_account_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilepaymentrequest',
            new_name='finance_mob_invoice_161280_idx',
            old_name='finance_mpr_invoice_status_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilepaymentrequest',
            new_name='finance_mob_provide_5ff813_idx',
            old_name='finance_mpr_provider_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentgatewayevent',
            new_name='finance_pay_provide_7cd9cb_idx',
            old_name='finance_pge_provider_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentgatewayevent',
            new_name='finance_pay_process_d1e347_idx',
            old_name='finance_pge_processed_idx',
        ),
        migrations.RemoveField(
            model_name='communicationtemplate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='schoolexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='integrationeventlog',
            name='direction',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=16),
        ),
        migrations.AlterField(
            model_name='integrationeventlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='integrationproviderconfig',
            name='provider_type',
            field=models.CharField(choices=[('BIOMETRIC', 'Biometric Attendance'), ('SMS', 'SMS Gateway'), ('WHATSAPP', 'WhatsApp Cloud API'), ('EMAIL', 'Email Gateway'), ('MTN_MOMO', 'MTN MoMo'), ('AIRTEL_MONEY', 'Airtel Money'), ('GOOGLE_MEET', 'Google Meet'), ('ZOOM', 'Zoom'), ('BIGBLUEBUTTON', 'BigBlueButton'), ('GOOGLE_LOGIN', 'Google Login'), ('MICROSOFT_LOGIN', 'Microsoft Login'), ('GPS', 'Vehicle GPS'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='meetingsessionlink',
            name='provider_type',
            field=models.CharField(choices=[('GOOGLE_MEET', 'Google Meet'), ('ZOOM', 'Zoom'), ('BIGBLUEBUTTON', 'BigBlueButton')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ssologinprovider',
            name='provider_type',
            field=models.CharField(choices=[('GOOGLE', 'Google'), ('MICROSOFT', 'Microsoft')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['cash_account', 'transaction_date'], name='finance_ban_cash_ac_b11bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['reference'], name='finance_ban_referen_7f49fc_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricattendanceevent',
            index=models.Index(fields=['external_person_id', 'event_time'], name='finance_bio_externa_41a606_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricattendanceevent',
            index=models.Index(fields=['processed'], name='finance_bio_process_1dc570_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationeventlog',
            index=models.Index(fields=['event_type', 'status', 'created_at'], name='finance_int_event_t_439fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationeventlog',
            index=models.Index(fields=['external_reference'], name='finance_int_externa_45fead_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationproviderconfig',
            index=models.Index(fields=['provider_type', 'is_active'], name='finance_int_provide_85815e_idx'),
        ),
    ]
