# Generated by Django 4.2.17 on 2026-07-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_communicationtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtemplate',
            name='message_type',
            field=models.CharField(choices=[('FEE_REMINDER', 'Fee reminder'), ('PAYMENT_RECEIPT', 'Payment receipt'), ('ABSENCE_ALERT', 'Absence alert'), ('URGENT_ANNOUNCEMENT', 'Urgent announcement'), ('PARENT_DIGEST', 'Parent digest')], max_length=32),
        ),
        migrations.AlterField(
            model_name='outboundmessagelog',
            name='message_type',
            field=models.CharField(choices=[('FEE_REMINDER', 'Fee reminder'), ('PAYMENT_RECEIPT', 'Payment receipt'), ('ABSENCE_ALERT', 'Absence alert'), ('URGENT_ANNOUNCEMENT', 'Urgent announcement'), ('PARENT_DIGEST', 'Parent digest')], max_length=32),
        ),
    ]
