# Generated by Django 5.2.16 on 2026-07-21 13:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_programme_pathways_subject_combinations'),
        ('education_frameworks', '0001_initial'),
        ('finance', '0012_alter_communicationtemplate_message_type_and_more'),
        ('orgsettings', '0006_merge_20260624_1447'),
        ('students', '0005_studentprofile_demographics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('access_type', models.CharField(choices=[('ONLINE_EXAM', 'Online examination access'), ('ASSESSMENT_RESULTS', 'Assessment results'), ('ASSESSMENT_REPORT', 'Assessment report card'), ('EXAM_RESULTS', 'Examination results'), ('EXAM_REPORT', 'Examination report card')], max_length=32)),
                ('calculation_basis', models.CharField(choices=[('CURRENT_TERM', 'Matching/current academic term invoices'), ('ALL_OPEN', 'All active invoices')], default='CURRENT_TERM', max_length=20)),
                ('rule_type', models.CharField(choices=[('FULL_PAYMENT', 'Require full payment'), ('MIN_PERCENT', 'Require minimum paid percentage'), ('MAX_BALANCE', 'Allow up to a maximum outstanding balance')], default='FULL_PAYMENT', max_length=20)),
                ('minimum_paid_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('maximum_outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allow_when_no_invoice', models.BooleanField(default=True, help_text='Keep access available when no invoice exists in the selected calculation basis.')),
                ('enforcement_mode', models.CharField(choices=[('ADVISORY', 'Advisory warning only'), ('BLOCK', 'Block access when not cleared')], default='ADVISORY', max_length=16)),
                ('user_message', models.CharField(blank=True, help_text='Message shown when the learner does not meet this policy.', max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_policies', to='academics.academicterm')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_policies', to='orgsettings.campus')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_policies', to='academics.level')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_policies', to='academics.program')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_policies', to='education_frameworks.educationstage')),
            ],
            options={
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClearanceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('ALL', 'All clearance-controlled access'), ('ONLINE_EXAM', 'Online examination access'), ('ASSESSMENT_RESULTS', 'Assessment results'), ('ASSESSMENT_REPORT', 'Assessment report card'), ('EXAM_RESULTS', 'Examination results'), ('EXAM_REPORT', 'Examination report card')], default='ALL', max_length=32)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=96)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_overrides', to='academics.academicterm')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_overrides_approved', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_overrides', to='students.studentprofile')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='finance.clearancepolicy')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ClearanceDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('ONLINE_EXAM', 'Online examination access'), ('ASSESSMENT_RESULTS', 'Assessment results'), ('ASSESSMENT_REPORT', 'Assessment report card'), ('EXAM_RESULTS', 'Examination results'), ('EXAM_REPORT', 'Examination report card')], max_length=32)),
                ('decision', models.CharField(choices=[('ALLOWED', 'Allowed'), ('ADVISED', 'Allowed with advisory'), ('BLOCKED', 'Blocked'), ('OVERRIDDEN', 'Allowed by override')], max_length=16)),
                ('source', models.CharField(choices=[('PORTAL', 'Portal'), ('ADMIN', 'Administrator check'), ('COMMAND', 'Command audit')], default='PORTAL', max_length=16)),
                ('invoiced_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paid_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_decision_logs', to='academics.academicterm')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_decisions_checked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_decision_logs', to='students.studentprofile')),
                ('override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='finance.clearanceoverride')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='finance.clearancepolicy')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='clearancepolicy',
            index=models.Index(fields=['access_type', 'is_active', 'priority'], name='finance_cle_access__d4bb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='clearanceoverride',
            index=models.Index(fields=['student', 'is_active', 'valid_from', 'valid_until'], name='finance_cle_student_89d52b_idx'),
        ),
        migrations.AddIndex(
            model_name='clearancedecisionlog',
            index=models.Index(fields=['student', 'access_type', 'created_at'], name='finance_cle_student_e7c44f_idx'),
        ),
    ]
