# Generated by Django 4.2.17 on 2026-06-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissions_crm_full_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admissionappointment',
            new_name='admissions__status_d6bb40_idx',
            old_name='admissions_appt_status_idx',
        ),
        migrations.RenameIndex(
            model_name='admissionlead',
            new_name='admissions__status_78f169_idx',
            old_name='admissions_lead_status_idx',
        ),
        migrations.RenameIndex(
            model_name='admissionlead',
            new_name='admissions__follow__06d1e3_idx',
            old_name='admissions_lead_follow_idx',
        ),
        migrations.RenameIndex(
            model_name='applicant',
            new_name='admissions__status_baa44a_idx',
            old_name='admissions_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='applicant',
            new_name='admissions__submitt_c3dd58_idx',
            old_name='admissions_online_created_idx',
        ),
    ]
