# Generated by Django 4.2.17 on 2026-06-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webpushsubscription',
            new_name='portals_web_user_id_5ff60b_idx',
            old_name='portals_web_user_id_712b33_idx',
        ),
        migrations.RenameIndex(
            model_name='webpushsubscription',
            new_name='portals_web_is_acti_2b64fd_idx',
            old_name='portals_web_is_acti_95ac7a_idx',
        ),
    ]
