# Generated by Django 5.2.11 on 2026-03-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hr.staffprofile'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_category',
            field=models.CharField(choices=[('TEACHING', 'Teaching'), ('NON_TEACHING', 'Non-teaching')], default='TEACHING', max_length=16),
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='hr.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headed_departments', to='hr.staffprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
