# Generated by Django 4.2.17 on 2026-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_consent_backup_alerts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'action', 'created_at'], name='audit_audit_user_id_575fab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', 'created_at'], name='audit_audit_action_0c0ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['path'], name='audit_audit_path_94701f_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['consent_type', 'accepted', 'recorded_at'], name='audit_conse_consent_c903ef_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['username', 'status', 'created_at'], name='audit_login_usernam_1308fc_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address', 'created_at'], name='audit_login_ip_addr_56d775_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousloginalert',
            index=models.Index(fields=['status', 'created_at'], name='audit_suspi_status_b5dadf_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousloginalert',
            index=models.Index(fields=['username', 'ip_address'], name='audit_suspi_usernam_4b0264_idx'),
        ),
    ]
