# Generated for EduManage universal time and attendance integration.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0001_initial"),
        ("hr", "0003_allowancetype_deductiontype_paygrade_payslip_and_more"),
        ("orgsettings", "0006_merge_20260624_1447"),
        ("students", "0005_studentprofile_demographics"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("code", models.CharField(max_length=120, unique=True)),
                ("serial_number", models.CharField(blank=True, db_index=True, max_length=160)),
                ("vendor", models.CharField(choices=[("GENERIC", "Generic / canonical API"), ("ZKTECO", "ZKTeco"), ("HIKVISION", "Hikvision"), ("SUPREMA", "Suprema"), ("OTHER", "Other vendor")], default="GENERIC", max_length=24)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("connection_mode", models.CharField(choices=[("PUSH", "Direct push / webhook"), ("PULL", "Server or vendor API pull"), ("EDGE", "Local edge connector"), ("FILE", "File / CSV import")], default="PUSH", max_length=16)),
                ("protocol", models.CharField(blank=True, max_length=80)),
                ("identity_namespace", models.CharField(default="default", help_text="Devices sharing the same user-number namespace can reuse one identity mapping registry.", max_length=80)),
                ("timezone_name", models.CharField(default="Africa/Kampala", max_length=64)),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("token_prefix", models.CharField(blank=True, db_index=True, max_length=16)),
                ("token_hash", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("clock_offset_seconds", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campus", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attendance_devices", to="orgsettings.campus")),
            ],
            options={"ordering": ("campus__name", "name")},
        ),
        migrations.CreateModel(
            name="AttendanceIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("namespace", models.CharField(default="default", max_length=80)),
                ("external_person_id", models.CharField(max_length=160)),
                ("person_type", models.CharField(choices=[("STUDENT", "Student"), ("STAFF", "Staff")], max_length=16)),
                ("card_number", models.CharField(blank=True, db_index=True, max_length=160)),
                ("source", models.CharField(default="MANUAL", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attendance_device_identities", to="hr.staffprofile")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attendance_device_identities", to="students.studentprofile")),
            ],
            options={"ordering": ("namespace", "external_person_id")},
        ),
        migrations.AddConstraint(
            model_name="attendanceidentity",
            constraint=models.UniqueConstraint(fields=("namespace", "external_person_id"), name="uniq_att_identity_namespace_person"),
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("person_type", models.CharField(choices=[("STUDENT", "Student"), ("STAFF", "Staff")], max_length=16)),
                ("expected_in", models.TimeField(blank=True, null=True)),
                ("expected_out", models.TimeField(blank=True, null=True)),
                ("late_grace_minutes", models.PositiveSmallIntegerField(default=10)),
                ("early_departure_grace_minutes", models.PositiveSmallIntegerField(default=10)),
                ("duplicate_window_seconds", models.PositiveIntegerField(default=90)),
                ("minimum_presence_minutes", models.PositiveIntegerField(default=0)),
                ("direction_strategy", models.CharField(choices=[("DEVICE", "Trust device IN/OUT direction"), ("FIRST_LAST", "First scan in / last scan out"), ("ALTERNATE", "Alternate IN and OUT scans")], default="FIRST_LAST", max_length=16)),
                ("weekdays", models.JSONField(blank=True, default=list, help_text="ISO weekday numbers: Monday=0 through Sunday=6. Blank means Monday-Friday.")),
                ("notify_parent_on_arrival", models.BooleanField(default=False)),
                ("notify_parent_on_departure", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campus", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attendance_policies", to="orgsettings.campus")),
            ],
            options={"ordering": ("person_type", "campus__name", "name")},
        ),
        migrations.CreateModel(
            name="AttendanceDailyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("person_type", models.CharField(choices=[("STUDENT", "Student"), ("STAFF", "Staff")], max_length=16)),
                ("status", models.CharField(choices=[("PRESENT", "Present"), ("LATE", "Late"), ("PARTIAL", "Partial day"), ("ABSENT", "Absent"), ("EXCUSED", "Excused")], db_index=True, default="PRESENT", max_length=16)),
                ("first_in", models.DateTimeField(blank=True, null=True)),
                ("last_out", models.DateTimeField(blank=True, null=True)),
                ("minutes_late", models.PositiveIntegerField(default=0)),
                ("minutes_early_departure", models.PositiveIntegerField(default=0)),
                ("minutes_present", models.PositiveIntegerField(default=0)),
                ("source_event_count", models.PositiveIntegerField(default=0)),
                ("open_presence", models.BooleanField(default=False)),
                ("manual_override", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campus", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attendance_daily_records", to="orgsettings.campus")),
                ("policy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="daily_records", to="attendance.attendancepolicy")),
                ("staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="daily_presence_records", to="hr.staffprofile")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="daily_presence_records", to="students.studentprofile")),
            ],
            options={"ordering": ("-date", "person_type", "id")},
        ),
        migrations.AddConstraint(
            model_name="attendancedailyrecord",
            constraint=models.UniqueConstraint(condition=models.Q(("student__isnull", False)), fields=("date", "student"), name="uniq_att_daily_student"),
        ),
        migrations.AddConstraint(
            model_name="attendancedailyrecord",
            constraint=models.UniqueConstraint(condition=models.Q(("staff__isnull", False)), fields=("date", "staff"), name="uniq_att_daily_staff"),
        ),
        migrations.CreateModel(
            name="AttendanceEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("PUSH", "Direct push"), ("PULL", "Pulled from vendor"), ("EDGE", "Edge connector"), ("FILE", "File import"), ("LEGACY", "Legacy integration API"), ("MANUAL", "Manual entry")], default="PUSH", max_length=16)),
                ("external_event_id", models.CharField(blank=True, db_index=True, max_length=180)),
                ("external_person_id", models.CharField(blank=True, db_index=True, max_length=160)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("received_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("direction", models.CharField(choices=[("IN", "In"), ("OUT", "Out"), ("BREAK_OUT", "Break out"), ("BREAK_IN", "Break in"), ("UNKNOWN", "Unknown")], default="UNKNOWN", max_length=16)),
                ("raw_direction", models.CharField(blank=True, max_length=80)),
                ("auth_method", models.CharField(choices=[("FACE", "Face"), ("FINGERPRINT", "Fingerprint"), ("RFID", "RFID / card"), ("PIN", "PIN"), ("QR", "QR code"), ("PALM", "Palm"), ("MOBILE", "Mobile"), ("UNKNOWN", "Unknown")], default="UNKNOWN", max_length=16)),
                ("event_code", models.CharField(blank=True, max_length=120)),
                ("event_hash", models.CharField(max_length=64, unique=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("processing_status", models.CharField(choices=[("RECEIVED", "Received"), ("PROCESSED", "Processed"), ("DUPLICATE", "Duplicate"), ("UNMATCHED", "Unmatched identity"), ("IGNORED", "Ignored"), ("ERROR", "Error")], db_index=True, default="RECEIVED", max_length=16)),
                ("error_message", models.TextField(blank=True)),
                ("clock_skew_seconds", models.IntegerField(default=0)),
                ("server_time_used", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("arrival_notified", models.BooleanField(default=False)),
                ("departure_notified", models.BooleanField(default=False)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="attendance.attendancedevice")),
                ("identity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="attendance.attendanceidentity")),
                ("staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="device_attendance_events", to="hr.staffprofile")),
                ("student", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="device_attendance_events", to="students.studentprofile")),
            ],
            options={"ordering": ("-occurred_at", "-id")},
        ),
        migrations.CreateModel(
            name="AttendanceAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("record", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="adjustments", to="attendance.attendancedailyrecord")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="AttendanceSyncCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cursor_key", models.CharField(default="events", max_length=80)),
                ("cursor_value", models.CharField(blank=True, max_length=255)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_cursors", to="attendance.attendancedevice")),
            ],
            options={"ordering": ("device", "cursor_key")},
        ),
        migrations.AddConstraint(
            model_name="attendancesynccursor",
            constraint=models.UniqueConstraint(fields=("device", "cursor_key"), name="uniq_att_sync_cursor"),
        ),
    ]
