# Generated by Django 4.2.17 on 2026-06-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0002_lms_links_discussions_progress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courseworkprogress',
            new_name='coursework__student_40582d_idx',
            old_name='coursework_student_material_idx',
        ),
        migrations.RenameIndex(
            model_name='courseworkprogress',
            new_name='coursework__student_060c32_idx',
            old_name='coursework_student_assign_idx',
        ),
    ]
