# Generated by Django 4.2.17 on 2026-03-01 00:00

from django.db import migrations, models
import django.db.models.deletion


def populate_campus(apps, schema_editor):
    ClassGroup = apps.get_model("academics", "ClassGroup")
    CourseOffering = apps.get_model("academics", "CourseOffering")
    Enrollment = apps.get_model("academics", "Enrollment")

    for o in CourseOffering.objects.select_related("class_group", "teacher").all():
        if o.campus_id:
            continue
        campus_id = None
        if o.class_group_id and getattr(o.class_group, "campus_id", None):
            campus_id = o.class_group.campus_id
        if campus_id is None and o.teacher_id and getattr(o.teacher, "campus_id", None):
            campus_id = o.teacher.campus_id
        if campus_id is not None:
            CourseOffering.objects.filter(pk=o.pk).update(campus_id=campus_id)

    for e in Enrollment.objects.select_related("offering", "student").all():
        if e.campus_id:
            continue
        campus_id = None
        if e.offering_id and getattr(e.offering, "campus_id", None):
            campus_id = e.offering.campus_id
        if campus_id is None and e.student_id and getattr(e.student, "campus_id", None):
            campus_id = e.student.campus_id
        if campus_id is not None:
            Enrollment.objects.filter(pk=e.pk).update(campus_id=campus_id)


class Migration(migrations.Migration):

    dependencies = [
        ("orgsettings", "0001_initial"),
        ("academics", "0001_initial"),
        ("teachers", "0002_teacherprofile_campus"),
        ("students", "0002_studentprofile_campus"),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orgsettings.campus",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orgsettings.campus",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orgsettings.campus",
            ),
        ),
        migrations.RunPython(populate_campus, migrations.RunPython.noop),
    ]
