# Generated by Django 4.2.17 on 2026-03-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_campus'),
        ('academics', '0002_campus_scoping'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('room', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.classgroup')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_streams', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ('class_group', 'name'),
                'unique_together': {('class_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=8)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('remark', models.CharField(blank=True, max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='academics.gradingscale')),
            ],
            options={
                'ordering': ('scale', 'order', '-min_score'),
                'unique_together': {('scale', 'grade')},
            },
        ),
    ]
