# Generated by Django 4.2.17 on 2026-07-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentscore',
            name='report_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='report_comment_ai_assisted',
            field=models.BooleanField(default=False),
        ),
    ]
