# Generated by Django 5.2.11 on 2026-03-03 14:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgsettings', '0003_campus_student_numbering'),
        ('teachers', '0002_teacherprofile_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('duty_type', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('WEEKEND', 'Weekend'), ('GENERAL', 'General')], default='GENERAL', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgsettings.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duty_rosters', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('teacher', 'date', 'duty_type')},
            },
        ),
    ]
