# Generated by Django 4.2.17 on 2026-06-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_subscription_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformauditevent',
            new_name='tenants_pla_action_ea814b_idx',
            old_name='tenants_pla_action__6226d0_idx',
        ),
        migrations.RenameIndex(
            model_name='platformauditevent',
            new_name='tenants_pla_tenant__bd854a_idx',
            old_name='tenants_pla_tenant__721b7b_idx',
        ),
        migrations.RenameIndex(
            model_name='platformauditevent',
            new_name='tenants_pla_actor_i_3e640a_idx',
            old_name='tenants_pla_actor_i_f6637b_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptioninvoice',
            new_name='tenants_sub_status_beb030_idx',
            old_name='tenants_sub_status_582d29_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantsubscription',
            new_name='tenants_ten_status_2ac43f_idx',
            old_name='tenants_ten_status_5debb4_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantsubscription',
            new_name='tenants_ten_payment_d8841d_idx',
            old_name='tenants_ten_payment_191b13_idx',
        ),
    ]
