# Generated by Django 4.2.17 on 2026-07-13 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgsettings', '0006_merge_20260624_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_studentprofile_demographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('', 'Unknown'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('current_medication', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('preferred_clinic_or_doctor', models.CharField(blank=True, max_length=180)),
                ('doctor_phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='students.studentprofile')),
            ],
            options={
                'ordering': ('student__last_name', 'student__first_name'),
            },
        ),
        migrations.CreateModel(
            name='SickbayVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='MILD', max_length=16)),
                ('complaint', models.CharField(max_length=200)),
                ('symptoms', models.TextField(blank=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('nurse_or_doctor_name', models.CharField(blank=True, max_length=150)),
                ('treatment_given', models.TextField(blank=True)),
                ('medicine_given', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_at', models.DateTimeField(blank=True, null=True)),
                ('parent_notification_method', models.CharField(blank=True, choices=[('', 'Not notified'), ('PHONE', 'Phone call'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PORTAL', 'Portal message'), ('IN_PERSON', 'In person')], max_length=16)),
                ('outcome', models.CharField(choices=[('OBSERVATION', 'Under observation'), ('TREATED', 'Treated'), ('RETURNED_TO_CLASS', 'Returned to class'), ('SENT_HOME', 'Sent home'), ('REFERRED', 'Referred to clinic/hospital'), ('EMERGENCY', 'Emergency escalation')], default='OBSERVATION', max_length=24)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sickbay_visits_attended', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgsettings.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sickbay_visits_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sickbay_visits', to='students.studentprofile')),
            ],
            options={
                'ordering': ('-visit_at', '-created_at'),
                'indexes': [models.Index(fields=['student', 'visit_at'], name='sickbay_sic_student_0b45b2_idx'), models.Index(fields=['campus', 'visit_at'], name='sickbay_sic_campus__1e71e3_idx'), models.Index(fields=['outcome', 'visit_at'], name='sickbay_sic_outcome_a58081_idx')],
            },
        ),
    ]
