# Generated by Django 5.2.11 on 2026-03-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_gradingscale_stream_graderange'),
        ('students', '0004_studentprofile_stream'),
        ('teachers', '0002_teacherprofile_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Grade Point Average', max_digits=4, null=True)),
                ('overall_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_subjects', models.PositiveIntegerField(default=0)),
                ('subjects_passed', models.PositiveIntegerField(default=0)),
                ('subjects_failed', models.PositiveIntegerField(default=0)),
                ('class_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('class_size', models.PositiveIntegerField(blank=True, null=True)),
                ('stream_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('stream_size', models.PositiveIntegerField(blank=True, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, help_text='Percentile in class', max_digits=5, null=True)),
                ('performance_trend', models.CharField(blank=True, help_text='IMPROVING, DECLINING, STABLE', max_length=16)),
                ('previous_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('gpa_change', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_at_risk', models.BooleanField(default=False)),
                ('risk_level', models.CharField(blank=True, help_text='LOW, MEDIUM, HIGH, CRITICAL', max_length=16)),
                ('risk_factors', models.JSONField(default=list, help_text='List of identified risk factors')),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discipline_incidents', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='students.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm')),
            ],
            options={
                'ordering': ('-term__year__name', 'term__order', 'student'),
            },
        ),
        migrations.CreateModel(
            name='AtRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('risk_factors', models.JSONField(default=list)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommended_actions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=16)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='teachers.teacherprofile')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to='teachers.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='students.studentprofile')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.studentperformancesnapshot')),
            ],
            options={
                'ordering': ('-created_at', '-severity'),
            },
        ),
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=8)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('subject_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_weak_area', models.BooleanField(default=False, help_text='Performance below expected threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='analytics.studentperformancesnapshot')),
            ],
            options={
                'ordering': ('snapshot', 'course'),
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_student_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('excellence_rate', models.DecimalField(blank=True, decimal_places=2, help_text='% scoring >= 80%', max_digits=5, null=True)),
                ('total_assessments', models.PositiveIntegerField(default=0)),
                ('assessments_published', models.PositiveIntegerField(default=0)),
                ('average_grading_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('performance_trend', models.CharField(blank=True, max_length=16)),
                ('previous_average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('score_improvement', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('department_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('above_department_average', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='teachers.teacherprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm')),
            ],
            options={
                'ordering': ('-term__year__name', 'term__order', 'teacher'),
            },
        ),
        migrations.CreateModel(
            name='ClassPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('average_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('median_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('highest_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lowest_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('students_excellent', models.PositiveIntegerField(default=0, help_text='GPA >= 3.5')),
                ('students_good', models.PositiveIntegerField(default=0, help_text='3.0 <= GPA < 3.5')),
                ('students_average', models.PositiveIntegerField(default=0, help_text='2.5 <= GPA < 3.0')),
                ('students_below_average', models.PositiveIntegerField(default=0, help_text='2.0 <= GPA < 2.5')),
                ('students_failing', models.PositiveIntegerField(default=0, help_text='GPA < 2.0')),
                ('at_risk_count', models.PositiveIntegerField(default=0)),
                ('critical_risk_count', models.PositiveIntegerField(default=0)),
                ('best_performing_subjects', models.JSONField(default=list, help_text='Top 3 subjects by average')),
                ('worst_performing_subjects', models.JSONField(default=list, help_text='Bottom 3 subjects by average')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='academics.stream')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm')),
            ],
            options={
                'ordering': ('-term__year__name', 'term__order', 'stream'),
                'unique_together': {('stream', 'term')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=8)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to='students.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm')),
            ],
            options={
                'ordering': ('student', 'term__year__name', 'term__order', 'course'),
                'indexes': [models.Index(fields=['student', 'term'], name='analytics_p_student_b6a84c_idx'), models.Index(fields=['course', 'term'], name='analytics_p_course__3f84f7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studentperformancesnapshot',
            index=models.Index(fields=['student', '-term'], name='analytics_s_student_82b896_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformancesnapshot',
            index=models.Index(fields=['is_at_risk'], name='analytics_s_is_at_r_cd0b81_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformancesnapshot',
            index=models.Index(fields=['risk_level'], name='analytics_s_risk_le_333c5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentperformancesnapshot',
            unique_together={('student', 'term')},
        ),
        migrations.AddIndex(
            model_name='atriskalert',
            index=models.Index(fields=['student', 'status'], name='analytics_a_student_2dac38_idx'),
        ),
        migrations.AddIndex(
            model_name='atriskalert',
            index=models.Index(fields=['severity', 'status'], name='analytics_a_severit_30e50e_idx'),
        ),
        migrations.AddIndex(
            model_name='atriskalert',
            index=models.Index(fields=['-created_at'], name='analytics_a_created_07cb0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectperformance',
            unique_together={('snapshot', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherperformancemetrics',
            unique_together={('teacher', 'term', 'course')},
        ),
    ]
