# Generated by Django 4.2.17 on 2026-06-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_intelligence_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['student', 'status'], name='analytics_i_student_297c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['alert', 'status'], name='analytics_i_alert_i_78df07_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrecommendation',
            index=models.Index(fields=['student', 'status'], name='analytics_s_student_e02dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrecommendation',
            index=models.Index(fields=['priority', 'status'], name='analytics_s_priorit_25fe5d_idx'),
        ),
    ]
