# Generated by Django 4.2.17 on 2026-03-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.tenant.orgsettings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                (
                    "logo",
                    models.FileField(blank=True, upload_to=apps.tenant.orgsettings.models.branding_upload_to),
                ),
                ("primary_color", models.CharField(blank=True, max_length=32)),
                ("secondary_color", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                (
                    "logo_override",
                    models.FileField(blank=True, upload_to=apps.tenant.orgsettings.models.branding_upload_to),
                ),
                ("primary_color_override", models.CharField(blank=True, max_length=32)),
                ("secondary_color_override", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campuses",
                        to="orgsettings.organizationprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orgsettings.campus",
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.AddConstraint(
            model_name="campus",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("code", "")),
                fields=("organization", "code"),
                name="uniq_campus_code_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("campus__isnull", True)),
                fields=("code",),
                name="uniq_featureflag_global_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("campus__isnull", False)),
                fields=("campus", "code"),
                name="uniq_featureflag_campus_code",
            ),
        ),
    ]
