# Generated by Django 4.2.17 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgsettings", "0002_statushistory_notification_actionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="student_number_format",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="campus",
            name="last_student_sequence",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
