# Generated by Django 4.2.17 on 2026-06-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgsettings', '0004_organizationprofile_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='tenant_domain',
            field=models.CharField(blank=True, help_text='School domain used to access this tenant, for example greenvalley.ac.ug.', max_length=253),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='tenant_schema_name',
            field=models.CharField(blank=True, help_text='SaaS tenant schema/slug for this school, for example green_valley_school.', max_length=63),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='tenant_status',
            field=models.CharField(blank=True, default='active', max_length=32),
        ),
    ]
