# Generated by Django 4.2.17 on 2026-06-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgsettings', '0002_normalize_feature_flag_codes'),
        ('orgsettings', '0005_organizationprofile_tenant_domain_and_more'),
    ]

    operations = [
    ]
