# Generated by Django 5.2.11 on 2026-03-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_gradingscale_stream_graderange'),
        ('exams', '0001_initial'),
        ('students', '0004_studentprofile_stream'),
        ('teachers', '0002_teacherprofile_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_mode',
            field=models.CharField(choices=[('PAPER_BASED', 'Paper-Based'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='PAPER_BASED', max_length=16),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, help_text='General instructions for all papers in this exam'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='allow_calculator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration for online exams', null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='passing_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text='Randomize question order for online exams'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='show_results_immediately',
            field=models.BooleanField(default=False, help_text='Show results after submission'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examscore',
            name='grade',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='examscore',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examscore',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('appeared_students', models.PositiveIntegerField(default=0)),
                ('passed_students', models.PositiveIntegerField(default=0)),
                ('failed_students', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('highest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lowest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('median_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='exams.exampaper')),
            ],
            options={
                'verbose_name_plural': 'Exam Analytics',
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='teachers.teacherprofile')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.exampaper')),
            ],
            options={
                'ordering': ('date', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='OnlineExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto-Submitted'), ('GRADED', 'Graded')], default='IN_PROGRESS', max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exampaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='students.studentprofile')),
            ],
            options={
                'ordering': ('-started_at',),
                'unique_together': {('paper', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('SHORT_ANSWER', 'Short Answer'), ('ESSAY', 'Essay'), ('FILL_BLANK', 'Fill in the Blank')], max_length=16)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=16)),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='exam_questions/')),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('option_a', models.CharField(blank=True, max_length=255)),
                ('option_b', models.CharField(blank=True, max_length=255)),
                ('option_c', models.CharField(blank=True, max_length=255)),
                ('option_d', models.CharField(blank=True, max_length=255)),
                ('correct_option', models.CharField(blank=True, help_text='A, B, C, or D', max_length=1)),
                ('correct_answer', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('marks', models.DecimalField(decimal_places=2, help_text='Marks for this question in this exam', max_digits=5)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exampaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.questionbank')),
            ],
            options={
                'ordering': ('paper', 'order'),
                'unique_together': {('paper', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=16)),
                ('admit_card_generated', models.BooleanField(default=False)),
                ('admit_card_generated_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='exams.examschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'ordering': ('seat_number',),
                'unique_together': {('schedule', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, help_text='A, B, C, or D for MCQ', max_length=1)),
                ('answer_text', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exams.onlineexamattempt')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examquestion')),
            ],
            options={
                'ordering': ('exam_question__order',),
                'unique_together': {('attempt', 'exam_question')},
            },
        ),
    ]
