# Generated by Django 4.2.17 on 2026-06-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_description_exam_exam_mode_exam_instructions_and_more'),
        ('exams', '0002_online_exam_workflow_hardening'),
    ]

    operations = [
    ]
