# Generated by Django 4.2.17 on 2026-06-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_merge_20260618_0937'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examanticheatevent',
            new_name='exams_exama_attempt_42b1d7_idx',
            old_name='exams_anticheat_idx',
        ),
    ]
