import apps.tenant.institutional.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0004_programme_pathways_subject_combinations"),
        ("education_frameworks", "0001_initial"),
        ("exams", "0006_external_exam_candidates"),
        ("orgsettings", "0006_merge_20260624_1447"),
        ("students", "0005_studentprofile_demographics"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("title", models.CharField(default="Learner Progress Report", max_length=160)),
                ("sections", models.JSONField(blank=True, default=list, help_text="Ordered section keys, for example identity, results, attendance, ecd, activities, finance, comments and signatures.")),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("show_position", models.BooleanField(default=False)),
                ("show_attendance", models.BooleanField(default=True)),
                ("show_clearance", models.BooleanField(default=False)),
                ("show_photo", models.BooleanField(default=True)),
                ("show_verification_code", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campus", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="orgsettings.campus")),
                ("level", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="academics.level")),
                ("stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="education_frameworks.educationstage")),
            ],
            options={"ordering": ("-is_default", "name")},
        ),
        migrations.AddConstraint(
            model_name="reporttemplate",
            constraint=models.UniqueConstraint(fields=("campus", "stage", "level", "name"), name="uniq_institutional_report_template_scope_name"),
        ),
        migrations.CreateModel(
            name="ResultPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("result_system", models.CharField(choices=[("GENERIC", "Percentage and grade"), ("ECD", "ECD developmental assessment"), ("PLE", "PLE aggregate and division"), ("UCE", "UCE aggregate or competency summary"), ("UACE", "UACE principal/subsidiary points"), ("GPA", "GPA and cumulative GPA")], default="GENERIC", max_length=16)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("priority", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campus", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="orgsettings.campus")),
                ("level", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="academics.level")),
                ("program", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="academics.program")),
                ("stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="education_frameworks.educationstage")),
            ],
            options={"ordering": ("-priority", "-is_default", "name")},
        ),
        migrations.CreateModel(
            name="ECDObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(choices=[("LANGUAGE", "Language development"), ("SOCIAL", "Social behaviour"), ("MOTOR", "Motor skills"), ("NUMERACY", "Early numeracy"), ("FEEDING", "Feeding"), ("ATTENDANCE", "Attendance habits"), ("HYGIENE", "Personal hygiene"), ("EMOTIONAL", "Emotional development"), ("CREATIVITY", "Creativity")], max_length=24)),
                ("rating", models.CharField(choices=[("ACHIEVED", "Achieved"), ("DEVELOPING", "Developing"), ("NEEDS_SUPPORT", "Needs support"), ("NOT_ASSESSED", "Not yet assessed")], default="NOT_ASSESSED", max_length=24)),
                ("observation", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("observed_on", models.DateField(default=django.utils.timezone.localdate)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_term", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ecd_observations", to="academics.academicterm")),
                ("recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ecd_observations", to="students.studentprofile")),
            ],
            options={"ordering": ("student__last_name", "domain")},
        ),
        migrations.AddConstraint(model_name="ecdobservation", constraint=models.UniqueConstraint(fields=("student", "academic_term", "domain"), name="uniq_ecd_term_domain")),
        migrations.CreateModel(
            name="LearnerSubjectCombination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("registered_on", models.DateField(default=django.utils.timezone.localdate)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subject_combination_registrations", to="academics.academicyear")),
                ("combination", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="learner_registrations", to="academics.subjectcombination")),
                ("registered_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subject_combination_registrations", to="students.studentprofile")),
            ],
            options={"ordering": ("-academic_year__name", "student__last_name")},
        ),
        migrations.AddConstraint(model_name="learnersubjectcombination", constraint=models.UniqueConstraint(fields=("student", "academic_year"), name="uniq_learner_combination_per_year")),
        migrations.CreateModel(
            name="CandidateDossier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("candidate_number", models.CharField(max_length=64)),
                ("photograph", models.ImageField(blank=True, upload_to="candidate_photos/%Y/%m/")),
                ("checklist", models.JSONField(blank=True, default=dict)),
                ("continuous_assessment_complete", models.BooleanField(default=False)),
                ("registration_status", models.CharField(choices=[("DRAFT", "Draft"), ("READY", "Ready for submission"), ("SUBMITTED", "Submitted"), ("APPROVED", "Approved"), ("WITHDRAWN", "Withdrawn")], default="DRAFT", max_length=16)),
                ("registration_reference", models.CharField(blank=True, max_length=128)),
                ("verification_token", models.CharField(default=apps.tenant.institutional.models._token, editable=False, max_length=64, unique=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="candidate_dossiers", to="exams.externalexamsession")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="candidate_dossiers", to="students.studentprofile")),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("external_session", "candidate_number")},
        ),
        migrations.AddConstraint(model_name="candidatedossier", constraint=models.UniqueConstraint(fields=("student", "external_session"), name="uniq_candidate_dossier_session_student")),
        migrations.AddConstraint(model_name="candidatedossier", constraint=models.UniqueConstraint(fields=("external_session", "candidate_number"), name="uniq_candidate_dossier_number")),
        migrations.CreateModel(
            name="CandidateMockCycle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("exam_date", models.DateField()),
                ("aggregate", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("division", models.CharField(blank=True, max_length=32)),
                ("points", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("mean_percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("notes", models.TextField(blank=True)),
                ("dossier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mock_cycles", to="institutional.candidatedossier")),
            ],
            options={"ordering": ("dossier", "exam_date")},
        ),
        migrations.AddConstraint(model_name="candidatemockcycle", constraint=models.UniqueConstraint(fields=("dossier", "name"), name="uniq_candidate_mock_cycle")),
        migrations.CreateModel(
            name="CandidateExamAttendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PRESENT", "Present"), ("ABSENT", "Absent"), ("LATE", "Late"), ("EXCUSED", "Excused")], default="PRESENT", max_length=16)),
                ("marked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("dossier", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exam_attendance", to="institutional.candidatedossier")),
                ("marked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("subject_registration", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attendance_records", to="exams.externalcandidatesubject")),
            ],
            options={"ordering": ("dossier", "subject_registration__subject__order")},
        ),
        migrations.AddConstraint(model_name="candidateexamattendance", constraint=models.UniqueConstraint(fields=("dossier", "subject_registration"), name="uniq_candidate_subject_attendance")),
        migrations.CreateModel(
            name="VerifiablePermit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permit_type", models.CharField(choices=[("CANDIDATE", "Candidate permit"), ("CLEARANCE", "Assessment clearance permit"), ("GATE", "Gate pass"), ("TRANSCRIPT", "Academic transcript"), ("REPORT", "Report card")], max_length=16)),
                ("title", models.CharField(max_length=160)),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("verification_token", models.CharField(default=apps.tenant.institutional.models._token, editable=False, max_length=64, unique=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("USED", "Used"), ("REVOKED", "Revoked"), ("EXPIRED", "Expired")], default="ACTIVE", max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="verifiable_permits", to="students.studentprofile")),
            ],
            options={"ordering": ("-issued_at",), "indexes": [models.Index(fields=["verification_token", "status"], name="institution_verifi_e4b2c4_idx")]},
        ),
        migrations.CreateModel(
            name="VisitationWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("visitor_limit_per_student", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                ("instructions", models.TextField(blank=True)),
                ("campus", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="visitation_windows", to="orgsettings.campus")),
            ],
            options={"ordering": ("-starts_at",)},
        ),
        migrations.AddConstraint(model_name="visitationwindow", constraint=models.UniqueConstraint(fields=("campus", "name", "starts_at"), name="uniq_campus_visitation_window")),
        migrations.CreateModel(
            name="VisitorRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("visitor_name", models.CharField(max_length=160)),
                ("identity_type", models.CharField(max_length=64)),
                ("identity_number", models.CharField(max_length=96)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("relationship", models.CharField(max_length=64)),
                ("purpose", models.CharField(blank=True, max_length=160)),
                ("arrived_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("departed_at", models.DateTimeField(blank=True, null=True)),
                ("collected_student", models.BooleanField(default=False)),
                ("student_returned_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="visitor_records", to="students.studentprofile")),
                ("verification_window", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="visitors", to="institutional.visitationwindow")),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-arrived_at",), "indexes": [models.Index(fields=["identity_number", "arrived_at"], name="institution_visito_3a6ddc_idx")]},
        ),
        migrations.RenameField(model_name="visitorrecord", old_name="verification_window", new_name="visitation_window"),
        migrations.CreateModel(
            name="MealService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service_date", models.DateField(default=django.utils.timezone.localdate)),
                ("meal", models.CharField(choices=[("BREAKFAST", "Breakfast"), ("LUNCH", "Lunch"), ("SUPPER", "Supper"), ("SNACK", "Snack"), ("OTHER", "Other")], max_length=16)),
                ("served_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("campus", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="meal_services", to="orgsettings.campus")),
                ("recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-service_date", "meal")},
        ),
        migrations.AddConstraint(model_name="mealservice", constraint=models.UniqueConstraint(fields=("campus", "service_date", "meal"), name="uniq_campus_daily_meal")),
        migrations.CreateModel(
            name="MealAttendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PRESENT", "Present"), ("MISSED", "Missed"), ("EXCUSED", "Excused"), ("SICK", "Sick")], default="PRESENT", max_length=16)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("marked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance", to="institutional.mealservice")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="meal_attendance", to="students.studentprofile")),
            ],
            options={"ordering": ("student__last_name", "student__first_name")},
        ),
        migrations.AddConstraint(model_name="mealattendance", constraint=models.UniqueConstraint(fields=("service", "student"), name="uniq_meal_student")),
        migrations.CreateModel(
            name="StudentProperty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("serial_number", models.CharField(blank=True, max_length=128)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("status", models.CharField(choices=[("IN_CUSTODY", "In custody"), ("RELEASED", "Released"), ("LOST", "Lost"), ("DAMAGED", "Damaged")], default="IN_CUSTODY", max_length=16)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("released_to", models.CharField(blank=True, max_length=160)),
                ("release_identity", models.CharField(blank=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                ("received_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="property_received", to=settings.AUTH_USER_MODEL)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="property_records", to="students.studentprofile")),
            ],
            options={"ordering": ("-received_at",)},
        ),
    ]
