# Generated by Django 4.2.17 on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="is_urgent",
            field=models.BooleanField(
                default=False,
                help_text="Urgent announcements can be broadcast through SMS/WhatsApp in Phase 2.",
            ),
        ),
    ]
