# Generated by Django 4.2.17 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentprofile_campus"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
