# Generated by Django 4.2.17 on 2026-03-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_gradingscale_stream_graderange'),
        ('students', '0003_studentprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.stream'),
        ),
    ]
