# Generated by Django 5.2.11 on 2026-03-03 16:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_allowancetype_deductiontype_paygrade_payslip_and_more'),
        ('students', '0004_studentprofile_stream'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ('route', 'order')},
        ),
        migrations.AlterModelOptions(
            name='studenttransportassignment',
            options={'ordering': ('route', 'stop__order', 'student__first_name')},
        ),
        migrations.AlterModelOptions(
            name='transportroute',
            options={'ordering': ('code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='transportroute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='routestop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Parent/Guardian contact for transport emergencies', max_length=128),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='service_type',
            field=models.CharField(choices=[('PICKUP_ONLY', 'Pickup Only'), ('DROPOFF_ONLY', 'Drop-off Only'), ('BOTH', 'Both Ways')], default='BOTH', max_length=16),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='special_needs',
            field=models.TextField(blank=True, help_text='Any special requirements or medical conditions'),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total route distance in km', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='fare_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly fare for this route', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning (Pickup)'), ('AFTERNOON', 'Afternoon (Drop-off)'), ('BOTH', 'Both')], default='BOTH', max_length=16),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Route start time', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_device_id',
            field=models.CharField(blank=True, help_text='GPS tracking device identifier', max_length=128),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='OPERATIONAL', max_length=16),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BUS', 'Bus'), ('VAN', 'Van'), ('CAR', 'Car')], default='BUS', max_length=16),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Stop sequence number'),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='transport.transportroute'),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='transport.routestop'),
        ),
        migrations.AlterField(
            model_name='studenttransportassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transport.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Driver name if not linked to staff', max_length=128)),
                ('license_number', models.CharField(max_length=64, unique=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=128)),
                ('emergency_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='hr.staffprofile')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='transportroute',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transport.driver'),
        ),
        migrations.CreateModel(
            name='ParentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PICKUP', 'Pickup Notification'), ('DROPOFF', 'Drop-off Notification'), ('DELAY', 'Delay Alert'), ('EMERGENCY', 'Emergency'), ('GENERAL', 'General')], max_length=16)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transport.studenttransportassignment')),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='RouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=16)),
                ('start_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transport.transportroute')),
            ],
            options={
                'ordering': ('route', 'day_of_week', 'start_time'),
                'unique_together': {('route', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='VehicleTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=5, null=True)),
                ('heading', models.PositiveIntegerField(blank=True, help_text='Compass heading 0-359', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_moving', models.BooleanField(default=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transportroute')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='transport.vehicle')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='transport_v_vehicle_d1e2f0_idx')],
            },
        ),
    ]
