# Generated by Django 4.2.17 on 2026-03-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_campus_admin_role'),
        ('users', '0002_role_userrole_user_roles'),
    ]

    operations = [
    ]
