# Generated by Django 5.2.11 on 2026-03-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_password_setup_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CAMPUS_ADMIN', 'Campus Admin'), ('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=32, unique=True),
        ),
    ]
