# Generated by Django 4.2.17 on 2026-06-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mobiledevice'),
        ('users', '0006_alter_role_code'),
    ]

    operations = [
    ]
