# Generated by Django 4.2.17 on 2026-06-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_0003_mobiledevice_0006_alter_role_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobiledevice',
            new_name='users_mobil_user_id_2e0ef4_idx',
            old_name='users_mobile_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='mobiledevice',
            new_name='users_mobil_push_to_387236_idx',
            old_name='users_mobile_push_idx',
        ),
    ]
