# Generated by Django 4.2.17 on 2026-06-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
        ('users', '0008_rename_users_mobile_user_active_idx_users_mobil_user_id_2e0ef4_idx_and_more'),
    ]

    operations = [
    ]
