# Generated by Django 4.2.17 on 2026-06-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_demographics'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizanswer',
            name='unique_answer_per_question',
        ),
        migrations.RemoveConstraint(
            model_name='quizattempt',
            name='unique_quiz_attempt_per_student',
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'student')},
        ),
    ]
