# Generated by Django 4.2.17 on 2026-05-04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0003_alter_parentprofile_results_access_pin_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentprofile",
            name="allow_sms_alerts",
            field=models.BooleanField(
                default=True,
                help_text="Parent consents to receive SMS alerts and reminders.",
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="allow_whatsapp_alerts",
            field=models.BooleanField(
                default=True,
                help_text="Parent consents to receive WhatsApp alerts and reminders.",
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="communication_consent_updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Last time communication consent settings were updated.",
            ),
        ),
    ]
