# Generated by Django 4.2.17 on 2026-07-13 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgsettings', '0006_merge_20260624_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parents', '0004_parentprofile_communication_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped')], default='CREATED', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parent_digests', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_digests', to='orgsettings.notification')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='parents.parentprofile')),
            ],
            options={
                'ordering': ('-window_end', '-created_at'),
                'indexes': [models.Index(fields=['parent', 'window_start', 'window_end'], name='parents_par_parent__f39b26_idx'), models.Index(fields=['status', 'sent_at'], name='parents_par_status_e5e74a_idx')],
                'unique_together': {('parent', 'window_start', 'window_end')},
            },
        ),
    ]
