# Generated by Django 4.2.17 on 2026-07-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_parentdigest'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='digest_email_enabled',
            field=models.BooleanField(default=False, help_text='Email Smart Parent Digest summaries when an email address is available.'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='digest_enabled',
            field=models.BooleanField(default=True, help_text='Parent should receive Smart Parent Digest summaries.'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='digest_pwa_enabled',
            field=models.BooleanField(default=True, help_text='Send Smart Parent Digest browser/PWA alerts when subscriptions are available.'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='digest_whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='Send Smart Parent Digest summaries on WhatsApp when consent and phone number are available.'),
        ),
    ]
