from django.urls import include, path
from django.contrib.auth import views as auth_views

from apps.tenant.users import auth_views as custom_auth_views
from apps.tenant.users import device_portal, profile_views
from apps.tenant.parents import views as parent_admin_views
from . import (
    capability_views,
    experience_views,
    public_views,
    pwa,
    search_views,
    student_parent_search_views,
    teacher_search_views,
    views,
)

urlpatterns = [
    path("status/", public_views.public_status, name="public_status"),
    path("manifest.webmanifest", pwa.manifest, name="pwa_manifest"),
    path("service-worker.js", pwa.service_worker, name="pwa_service_worker"),
    path("pwa/push-readiness/", pwa.push_readiness, name="pwa_push_readiness"),
    path("pwa/push-subscribe/", pwa.push_subscribe, name="pwa_push_subscribe"),
    path("pwa/push-unsubscribe/", pwa.push_unsubscribe, name="pwa_push_unsubscribe"),
    path("platform/", include("apps.public.tenants.platform_urls")),
    path("apply/", include("apps.tenant.admissions.public_urls")),
    path("messages/", include("apps.tenant.messaging.urls")),
    path("notifications/", include("apps.tenant.orgsettings.alert_urls")),
    path("", views.landing_page, name="landing_page"),
    path("login/", custom_auth_views.CustomLoginView.as_view(), name="login"),
    path("logout/", custom_auth_views.logout_view, name="logout"),
    path("password-reset/", custom_auth_views.CustomPasswordResetView.as_view(), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_done.html"), name="password_reset_done"),
    path("password-reset/<uidb64>/<token>/", custom_auth_views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password-reset/complete/", auth_views.PasswordResetCompleteView.as_view(template_name="auth/password_reset_complete.html"), name="password_reset_complete"),
    path("change-password/", custom_auth_views.change_password, name="change_password"),
    path("profile/", profile_views.user_profile, name="user_profile"),
    path("devices/", device_portal.my_devices, name="my_devices"),
    path("devices/<int:pk>/deactivate/", device_portal.deactivate_my_device, name="my_device_deactivate"),
    path("admin/", views.admin_home, name="admin_home"),
    path("admin/capabilities/", capability_views.admin_capabilities, name="admin_capabilities_home"),
    path("admin/enterprise/", include("apps.tenant.portals.enterprise_urls")),
    path("admin/audit/", include("apps.tenant.audit.routes")),
    path("admin/communication/", experience_views.admin_communication_center, name="admin_communication_center"),
    path("admin/school-setup/", experience_views.admin_school_setup_guide, name="admin_school_setup_guide"),
    path("admin/school-health/", experience_views.admin_school_health_score, name="admin_school_health_score"),
    path("admin/school-health/data/", experience_views.admin_school_health_score_data, name="admin_school_health_score_data"),
    path("admin/system-status/", experience_views.admin_system_status, name="admin_system_status"),
    path("admin/search/", search_views.global_search, name="admin_global_search"),
    path("admin/students/", include("apps.tenant.students.urls")),
    path("admin/teachers/", include("apps.tenant.teachers.urls")),
    path("admin/parents/", include("apps.tenant.parents.urls")),
    path("admin/academics/", include("apps.tenant.academics.urls")),
    path("admin/users/", include("apps.tenant.users.urls")),
    path("admin/integrations/", include("apps.tenant.finance.connectors")),
    path("admin/attendance/", include("apps.tenant.attendance.admin_urls")),
    path("admin/assessments/", include("apps.tenant.assessments.admin_urls")),
    path("admin/finance/", include("apps.tenant.finance.admin_urls")),
    path("admin/announcements/", include("apps.tenant.announcements.admin_urls")),
    path("admin/coursework/", include("apps.tenant.coursework.admin_urls")),
    path("admin/quizzes/", include("apps.tenant.quizzes.admin_routes")),
    path("admin/activities/", include("apps.tenant.activities.admin_urls")),
    path("admin/duty/", include("apps.tenant.duty.admin_urls")),
    path("admin/timetable/", include("apps.tenant.timetable.admin_urls")),
    path("admin/discipline/", include("apps.tenant.discipline.admin_urls")),
    path("admin/sickbay/", include("apps.tenant.sickbay.admin_urls")),
    path("admin/grievances/", include("apps.tenant.grievances.admin_urls")),
    path("admin/documents/", include("apps.tenant.documents.admin_urls")),
    path("admin/transport/", include("apps.tenant.transport.admin_urls")),
    path("admin/library/", include("apps.tenant.library.admin_urls")),
    path("admin/hostels/", include("apps.tenant.hostels.admin_urls")),
    path("admin/inventory/", include("apps.tenant.inventory.admin_urls")),
    path("admin/exams/", include("apps.tenant.exams.admin_urls")),
    path("admin/analytics/", include("apps.tenant.analytics.admin_urls")),
    path("admin/reports/", include("apps.tenant.reports.admin_urls")),
    path("admin/settings/", include("apps.tenant.orgsettings.admin_urls")),
    path("admin/admissions/", include("apps.tenant.admissions.admin_urls")),
    path("admin/hr/", include("apps.tenant.hr.admin_urls")),
    path("teacher/", views.teacher_home, name="teacher_home"),
    path("teacher/capabilities/", capability_views.teacher_capabilities, name="teacher_capabilities_home"),
    path("teacher/search/", teacher_search_views.teacher_search, name="teacher_global_search"),
    path("teacher/attendance/", include("apps.tenant.attendance.teacher_urls")),
    path("teacher/assessments/", include("apps.tenant.assessments.teacher_urls")),
    path("teacher/announcements/", include("apps.tenant.announcements.teacher_urls")),
    path("teacher/coursework/", include("apps.tenant.coursework.teacher_urls")),
    path("teacher/quizzes/", include("apps.tenant.quizzes.teacher_urls")),
    path("teacher/timetable/", include("apps.tenant.timetable.teacher_urls")),
    path("teacher/discipline/", include("apps.tenant.discipline.teacher_urls")),
    path("teacher/grievances/", include("apps.tenant.grievances.teacher_urls")),
    path("teacher/documents/", include("apps.tenant.documents.teacher_urls")),
    path("teacher/exams/", include("apps.tenant.exams.teacher_urls")),
    path("teacher/payroll/", include("apps.tenant.hr.staff_urls")),
    path("student/id-card/", include("apps.tenant.students.self_urls")),
    path("student/", views.student_home, name="student_home"),
    path("student/capabilities/", capability_views.student_capabilities, name="student_capabilities_home"),
    path("student/search/", student_parent_search_views.student_search, name="student_global_search"),
    path("student/attendance/", include("apps.tenant.attendance.student_urls")),
    path("student/results/", include("apps.tenant.assessments.student_urls")),
    path("student/finance/", include("apps.tenant.finance.student_urls")),
    path("student/announcements/", include("apps.tenant.announcements.student_urls")),
    path("student/coursework/", include("apps.tenant.coursework.student_urls")),
    path("student/quizzes/", include("apps.tenant.quizzes.student_urls")),
    path("student/timetable/", include("apps.tenant.timetable.student_urls")),
    path("student/discipline/", include("apps.tenant.discipline.student_urls")),
    path("student/sickbay/", include("apps.tenant.sickbay.student_urls")),
    path("student/documents/", include("apps.tenant.documents.student_urls")),
    path("student/transport/", include("apps.tenant.transport.student_urls")),
    path("student/library/", include("apps.tenant.library.student_urls")),
    path("student/hostels/", include("apps.tenant.hostels.student_urls")),
    path("student/exams/", include("apps.tenant.exams.student_urls")),
    path("parent/", views.parent_home, name="parent_home"),
    path("parent/capabilities/", capability_views.parent_capabilities, name="parent_capabilities_home"),
    path("parent/search/", student_parent_search_views.parent_search, name="parent_global_search"),
    path("parent/digests/", parent_admin_views.parent_digest_history, name="parent_digest_history"),
    path("parent/account/results-pin/", views.parent_results_pin_security, name="parent_results_pin_security"),
    path("parent/account/message-preferences/", views.parent_communication_preferences, name="parent_communication_preferences"),
    path("parent/attendance/", include("apps.tenant.attendance.parent_urls")),
    path("parent/results/", include("apps.tenant.assessments.parent_urls")),
    path("parent/finance/", include("apps.tenant.finance.parent_urls")),
    path("parent/announcements/", include("apps.tenant.announcements.parent_urls")),
    path("parent/coursework/", include("apps.tenant.coursework.parent_urls")),
    path("parent/exams/", include("apps.tenant.exams.parent_urls")),
    path("parent/discipline/", include("apps.tenant.discipline.parent_urls")),
    path("parent/sickbay/", include("apps.tenant.sickbay.parent_urls")),
    path("parent/grievances/", include("apps.tenant.grievances.parent_urls")),
    path("parent/documents/", include("apps.tenant.documents.parent_urls")),
    path("parent/transport/", include("apps.tenant.transport.parent_urls")),
    path("parent/library/", include("apps.tenant.library.parent_urls")),
    path("parent/hostels/", include("apps.tenant.hostels.parent_urls")),
    path("parent/students/", include("apps.tenant.students.parent_urls")),
]
