FIELD_REGISTRY = [
    {"category": "School", "label": "School name", "binding": "school.name", "kind": "field"},
    {"category": "School", "label": "School logo", "binding": "school.logo", "kind": "image"},
    {"category": "School", "label": "School email", "binding": "school.email", "kind": "field"},
    {"category": "School", "label": "School phone", "binding": "school.phone", "kind": "field"},
    {"category": "School", "label": "School address", "binding": "school.address", "kind": "field"},
    {"category": "Campus", "label": "Campus name", "binding": "campus.name", "kind": "field"},
    {"category": "Campus", "label": "Campus code", "binding": "campus.code", "kind": "field"},
    {"category": "Campus", "label": "Campus logo", "binding": "campus.logo", "kind": "image"},
    {"category": "Learner", "label": "Student name", "binding": "student.full_name", "kind": "field"},
    {"category": "Learner", "label": "First name", "binding": "student.first_name", "kind": "field"},
    {"category": "Learner", "label": "Last name", "binding": "student.last_name", "kind": "field"},
    {"category": "Learner", "label": "Student number", "binding": "student.student_id", "kind": "field"},
    {"category": "Learner", "label": "Learner ID", "binding": "student.learner_id", "kind": "field"},
    {"category": "Learner", "label": "Student email", "binding": "student.email", "kind": "field"},
    {"category": "Learner", "label": "Date of birth", "binding": "student.date_of_birth", "kind": "field"},
    {"category": "Learner", "label": "Class", "binding": "student.class", "kind": "field"},
    {"category": "Learner", "label": "Stream", "binding": "student.stream", "kind": "field"},
    {"category": "Learner", "label": "Student photo", "binding": "student.photo", "kind": "image"},
    {"category": "Academic", "label": "Term / semester", "binding": "academic.term", "kind": "field"},
    {"category": "Academic", "label": "Academic year", "binding": "academic.year", "kind": "field"},
    {"category": "Academic", "label": "Mean score", "binding": "academic.mean", "kind": "field"},
    {"category": "Academic", "label": "Overall grade", "binding": "academic.overall_grade", "kind": "field"},
    {"category": "Academic", "label": "Overall remark", "binding": "academic.overall_remark", "kind": "field"},
    {"category": "Document", "label": "Reference", "binding": "document.reference", "kind": "field"},
    {"category": "Document", "label": "Issue date", "binding": "document.issue_date", "kind": "field"},
    {"category": "Document", "label": "Verification QR", "binding": "document.verification_url", "kind": "qr"},
    {"category": "Academic", "label": "Results table", "binding": None, "kind": "results_table"},
]

SAMPLE_VALUES = {
    "school.name": "Green Valley School",
    "school.email": "office@example.edu",
    "school.phone": "+256 700 000000",
    "school.address": "Kampala, Uganda",
    "campus.name": "Main Campus",
    "campus.code": "MAIN",
    "student.full_name": "NAKATO SARAH",
    "student.first_name": "Sarah",
    "student.last_name": "Nakato",
    "student.student_id": "GVS/2026/0045",
    "student.learner_id": "EMIS-000045",
    "student.email": "sarah@example.edu",
    "student.date_of_birth": "14 Mar 2011",
    "student.class": "Senior Four",
    "student.stream": "East",
    "academic.term": "Term Two",
    "academic.year": "2026",
    "academic.mean": "78.4%",
    "academic.overall_grade": "A",
    "academic.overall_remark": "Excellent progress",
    "document.reference": "EDU-2026-000045",
    "document.issue_date": "10 Aug 2026",
}
