# Generated by Django 5.2.11 on 2026-03-03 14:36

import apps.tenant.activities.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_staffprofile_reports_to_staffprofile_staff_category_and_more'),
        ('orgsettings', '0003_campus_student_numbering'),
        ('students', '0004_studentprofile_stream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('CLUB', 'Club'), ('SPORT', 'Sport'), ('RELIGIOUS', 'Religious'), ('CO_CURRICULAR', 'Co-curricular'), ('GENERAL', 'General')], default='GENERAL', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('meeting_day', models.CharField(blank=True, max_length=32)),
                ('meeting_time', models.CharField(blank=True, max_length=32)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('poster', models.FileField(blank=True, null=True, upload_to=apps.tenant.activities.models.activities_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgsettings.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_activities', to='hr.staffprofile')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ActivityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='activities.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_memberships', to='students.studentprofile')),
            ],
            options={
                'ordering': ('-joined_at',),
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
